name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto si tu rama principal es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Especifica tu versión de Node.js aquí

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build the project
        run: |
          cd frontend
          npm run build

      - name: Configure Git
        run: |
          git config --global user.name "Emanuel Cabrera Novoa"
          git config --global user.email "emanuelcabreranovoa@hotmail.com"

      - name: Deploy to GitHub Pages
        run: |
          cd frontend
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

